Repository MarkGotLasagna/DWS, pull requests merged in 2024-05, with the labels that each got.

#13 Create single files for each correlation method and refactoring
  MATLAB/kendall_plot_peaks.m
  MATLAB/main.m
  MATLAB/n_plot_peaks.m
  MATLAB/norm_plot_peaks.m
  MATLAB/pearson_plot_peaks.m
  MATLAB/spearman_plot_peaks.m
  MATLAB/utils/column_smooth.m
  MATLAB/utils/correlations/coeff_correlation.m
  MATLAB/utils/correlations/norm_correlation.m
  MATLAB/utils/local_normalize.m
Labels: enhancement, help wanted

#15 added documentation
  MATLAB/utils/column_smooth.m
  MATLAB/utils/local_normalize.m
Labels: documentation

#16 Famous indexes and various percentile plots
  .gitignore
  MATLAB/kendall_plot_peaks.m
  MATLAB/ln_plot_peaks.m
  MATLAB/main.m
  MATLAB/n_plot_peaks.m
  MATLAB/norm_plot_peaks.m
  MATLAB/p200_plot_peaks.m
  MATLAB/p300_plot_peaks.m
  MATLAB/pearson_plot_peaks.m
  MATLAB/plot_peaks.m
  MATLAB/plot_pics.m
  MATLAB/spearman_plot_peaks.m
  MATLAB/utils/column_smooth.m
  MATLAB/utils/correlations/coeff_correlation.m
  MATLAB/utils/correlations/norm_correlation.m
  MATLAB/utils/local_normalize.m
  TODO.md
Labels: enhancement, help wanted, High priority
